### Supprimer shovel
DELETE http://localhost:29672/api/shovels/vhost/%2F/shovel_externe_message_send_to_interne_message_send
Content-Type: application/json
Authorization: Basic guest guest

### Mettre à jour shovel
PUT http://localhost:29672/api/parameters/shovel/%2f/shovel_externe_message_send_to_interne_message_send
Content-Type: application/json
Authorization: Basic guest guest

{
  "value": {
    "src-queue": "message.forward",
    "src-uri": [
      "amqp://"
    ],
    "dest-uri": [
      "amqp://rabbitmq-interne"
    ],
    "dest-exchange": "message.send"
  }
}